-- MySQL Script generated by MySQL Workbench
-- 04/18/16 10:39:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Renters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Renters` (
  `renterId` INT NOT NULL,
  `address` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(150) NULL,
  PRIMARY KEY (`renterId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5;


-- -----------------------------------------------------
-- Table `mydb`.`Owners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Owners` (
  `ownerId` INT NOT NULL,
  `email` VARCHAR(150) NULL,
  `name` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  PRIMARY KEY (`ownerId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Complains`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Complains` (
  `complainId` INT NOT NULL,
  `renterId` INT NOT NULL,
  `ownerId` INT NOT NULL,
  `solved` TINYINT(1) NULL,
  `priority` TINYINT NULL,
  `message` TEXT NULL,
  `createdOn` DATETIME NULL,
  `solvedOn` DATETIME NULL,
  INDEX `fk_Complains_Renters_idx` (`renterId` ASC),
  INDEX `fk_Complains_Owners1_idx` (`ownerId` ASC),
  PRIMARY KEY (`complainId`),
  CONSTRAINT `fk_Complains_Renters`
    FOREIGN KEY (`renterId`)
    REFERENCES `mydb`.`Renters` (`renterId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Complains_Owners1`
    FOREIGN KEY (`ownerId`)
    REFERENCES `mydb`.`Owners` (`ownerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
